<?php

use Illuminate\Database\Seeder;

class RangesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       
        DB::table('ranges')->insert([
            'unit_name'=>'A',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'A1',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'A2',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'A3',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VLL',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VLN',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'V12',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'V23',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'V31',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'V1',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'V2',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'V3',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'W',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'W1',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'W2',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'W3',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VAR',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VAR1',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VAR2',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VAR3',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VA',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VA1',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VA2',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'VA3',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'PF',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'PF1',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'PF2',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'PF3',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'F',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'FVAh',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'FWh',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'FVARh',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'RVAh',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'RWh',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'RVARh',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'OnH',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'FRun',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'RRun',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'INTR',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'PD',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'RD',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'MaxMD',
            'min'=>'0',
            'max'=>'100',
        ]);
        DB::table('ranges')->insert([
            'unit_name'=>'MaxDM',
            'min'=>'0',
            'max'=>'100',
        ]);
    }
}
